source 'https://rubygems.org'

gem 'rails', '~> 8.0.4'
gem 'sqlite3', '>= 2.1'
gem 'puma', '>= 5.0'
gem 'tzinfo-data', platforms: %i[windows jruby]

gem 'my_api_client', path: '../..'
gem 'benchmark'
gem 'cgi'

group :development, :test do
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'rspec-rails'
end
