# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jbuilder', '~> 2.0'
gem 'my_api_client', path: '../..'
gem 'rails', '~> 4.2.11'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'sprockets', '~> 3.0' # for ruby 2.4

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails'
end

group :development do
  gem 'spring'
  gem 'web-console', '~> 2.0'
end
