require:
  - rubocop-performance
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - rails_app/**/*
    - vendor/bundle/**/*

Layout/LineLength:
  Max: 100
  Exclude:
    - my_api/config/application.rb

Metrics/BlockLength:
  Exclude:
    - "my_api_client.gemspec"
    - "lib/my_api_client/rspec/matchers/**/*"
    - "spec/**/*"
    - "my_api/spec/**/*"

Metrics/MethodLength:
  Max: 15

Naming/AccessorMethodName:
  Exclude:
    - example/api_clients/**/*
    - spec/lib/my_api_client/rspec/matchers/be_handled_as_an_error_spec.rb

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

RSpec/DescribeClass:
  Exclude:
    - "spec/integrations/api_clients/**/*"
    - "spec/lib/my_api_client/rspec/matchers/**/*"

RSpec/ExampleLength:
  Max: 10

RSpec/FilePath:
  Exclude:
    - "spec/lib/my_api_client/integrations/**/*"
    - "spec/lib/my_api_client/errors/**/*"
    - "spec/lib/my_api_client/rspec/**/*"

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 4
