# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jets', '~> 3.2.0'

gem 'dynomite'

# See: https://github.com/boltops-tools/jets/issues/523
gem 'nokogiri', '~> 1.14.2'

# development and test groups are not bundled as part of the deployment
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'puma'
  gem 'rack'
  gem 'shotgun'
end

group :test do
  gem 'capybara'
  gem 'launchy'
  gem 'rspec'
  gem 'rspec_junit_formatter'
end
