# frozen_string_literal: true

source 'https://rubygems.org'

gem 'my_api_client', path: '../..'
gem 'benchmark'
gem 'cgi'
gem 'puma', '>= 5.0'
gem 'rails', '~> 7.2.1'
gem 'sqlite3', '>= 1.4'

gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'rspec-rails'
end
