# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'bootsnap', '>= 1.1.0', require: false
gem 'my_api_client', path: '../..'
gem 'rails', '~> 5.2.4'
gem 'sprockets', '~> 3.0' # for ruby 2.4

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails'
end

group :development do
  gem 'spring'
end
